---
# Naor Golan
# Sonia Iusupova
- name: Configure Cortex (AD/DC + DNS + SMB) without new modules
  hosts: cortex
  gather_facts: no
  tasks:
    - name: Install AD-DS and DNS
      ansible.windows.win_feature:
        name:
          - AD-Domain-Services
          - DNS
        include_management_tools: true
        state: present

    - name: Set local Administrator password (Domain Admin password)
      ansible.windows.win_user:
        name: Administrator
        password: "Naor1998"
        state: present

    - name: Promote DC to new forest (PowerShell)
      ansible.windows.win_shell: |
        Install-ADDSForest `
          -DomainName "net.runner" `
          -DomainNetbiosName "NETRUNNER" `
          -SafeModeAdministratorPassword (ConvertTo-SecureString "Naor1998" -AsPlainText -Force) `
          -InstallDNS `
          -Force

    - name: Reboot after promotion
      ansible.windows.win_reboot:
        msg: "Rebooting after domain promotion"
        pre_reboot_delay: 60

    - name: Ensure forward DNS zone exists (PowerShell)
      ansible.windows.win_shell: |
        if (-not (Get-DnsServerZone -Name "net.runner" -ErrorAction SilentlyContinue)) {
          Add-DnsServerPrimaryZone -Name "net.runner" -ReplicationScope "Domain"
        }

    - name: Add A record for cortex (PowerShell)
      ansible.windows.win_shell: |
        Add-DnsServerResourceRecordA -ZoneName "net.runner" -Name "cortex" -IPv4Address "100.65.1.125" -CreatePtr

    - name: Create folder for SMB share
      ansible.windows.win_file:
        path: "C:\\Shares\\Public"
        state: directory

    - name: Create SMB share (PowerShell)
      ansible.windows.win_shell: |
        if (-not (Get-SmbShare -Name "Public" -ErrorAction SilentlyContinue)) {
          New-SmbShare -Name "Public" -Path "C:\\Shares\\Public" -FullAccess Everyone
        }

