---
# Naor Golan
# Sonia Iusupova

- name: Configure Cortex (AD/DC + DNS + SMB)
  hosts: cortex
  gather_facts: no
  tasks:
    - name: Install AD-DS and DNS
      ansible.windows.win_feature:
        name:
          - AD-Domain-Services
          - DNS
        include_management_tools: true
        state: present

    - name: Set local Administrator password (Domain Admin password)
      ansible.windows.win_user:
        name: Administrator
        password: "Naor1998"
        state: present

    - name: Promote DC to new forest
      microsoft.ad.domain:
        dns_domain_name: "net.runner"
        domain_netbios_name: "NETRUNNER"
        install_dns: true
        safe_mode_password: "Br@indance123!"   # must meet complexity
        create_dns_delegation: false
      register: domain_setup

    - name: Reboot the DC if required
      ansible.windows.win_reboot:
        msg: "Reboot after promoting DC"
        pre_reboot_delay: 60
      when: domain_setup.reboot_required

    - name: Ensure forward zone exists
      ansible.windows.win_dns_zone:
        name: "net.runner"
        type: primary
        replication: Domain
        state: present

    - name: Add A record for cortex
        # If you want host only, use name: "cortex"
      ansible.windows.win_dns_record:
        zone: "net.runner"
        name: "cortex.net.runner"
        type: A
        value: "100.65.1.125"
        state: present

    - name: Create folder for SMB share
      ansible.windows.win_file:
        path: "C:\\Shares\\Public"
        state: directory

    - name: Create SMB share
      ansible.windows.win_share:
        name: "Public"
        description: "Public SMB Share"
        path: "C:\\Shares\\Public"
        full: "Everyone"
        state: present
